### ISSUE TITLE
In line radio buttons

### ISSUE THREAD

**Issue by Liglio** [victorpopkov/react-ui-icheck#1]
Hi,
How do I put the radio buttons in line? I tried to change the attribute in RadioGroup to radioWrapClassName="form-check-inline". The radio buttons became in line, but the behavior it is not normal.

**Comment by victorpopkov** [comment]
This library doesn't bundle any styles at this point so it's up to the user how to handle the inline behaviour.

> The radio buttons became in line, but the behaviour is not normal.

Why not? If you are using Bootstrap 4 and by the "behaviour" you mean the method of inlining checkboxes or radios on the same horizontal row, then the appropriate method is:

https://getbootstrap.com/docs/4.0/components/forms/#inline

You can achieve the same result by using the `radioWrapClassName="form-check form-check-inline"` of the  `RadioGroup` component you have mentioned earlier.

On the other hand, if by the "behaviour" you mean the clicking area issues, then most likely you are using the `increaseArea` prop. I would avoid using it at all in the first place.

I have updated the website demos to include the inline examples: http://github.victorpopkov.com/react-ui-icheck/

**Comment by victorpopkov** [comment]
Closing this for now as the inline behaviour seems to be fine.

Feel free to open a new issue if needed and thank you for your interest to this library in the first place.
