### ISSUE TITLE
RadioGroup behaving like CheckboxGroup when using the setState from useState hook

### ISSUE THREAD

**Issue by Iman78** [victorpopkov/react-ui-icheck#4]
Hello,

Like I said in the title, the Radios in a RadioGroup are behaving like a checkboxes ( that cannot be unchecked though ) when  using the setState from useState hook in the onChange handler prop. It does not seem to mess with the behavior of the checkboxes though.
Here's the component's code.

`
function App() {
  const [state, setState]= useState({value: 'hello'});
  return (
    <div >
      <CheckboxGroup
        checkboxWrapClassName="form-check"
        checkboxWrapTag="div"
      >
        <Checkbox
          checkboxClass="icheckbox_square-blue"
          increaseArea="30%"
          value ="check"
          label="#checkbox-1"
          onChange={(e, value, m) => {setState({value : e.target.value})}}
        />
        <Checkbox
          checkboxClass="icheckbox_square-blue"
          increaseArea="30%"
          value ="check2"
          label="#checkbox-1"
          onChange={(e, value, m) => {setState({value : e.target.value})}}
        />
        </CheckboxGroup>

        <RadioGroup
        onChange={(e, value) => {setState({value : e.target.value})}}
        name="radio"
        radioWrapClassName="form-check"
        radioWrapTag="div"
      >
        <Radio
          label="#radio-1"
          radioClass="iradio_square-blue"
          value="radio1"
        />
        <Radio
          label="#radio-1"
          radioClass="iradio_square-blue"
          value="radio2"
        />
      </RadioGroup>
      <div> {state.value}</div>
    </div>
  );
}
`

**Comment by victorpopkov** [comment]
Thank you for your interest.

It's expected behaviour. The `RadioGroup` in your example should have the `value` prop that corresponds to the current state one:

```javascript
import { Checkbox, Radio, RadioGroup } from 'react-ui-icheck';
import React, { useState } from 'react';

function App() {
  const [state, setState] = useState({ value: 'hello' });
  return (
    <div>
      <Checkbox
        checkboxClass="icheckbox_square-blue"
        label="#checkbox-1"
        value="check"
        onChange={(e) => setState({ value: e.target.value })}
      />
      <Checkbox
        checkboxClass="icheckbox_square-blue"
        label="#checkbox-1"
        value="check2"
        onChange={(e) => setState({ value: e.target.value })}
      />
      <RadioGroup
        name="radio"
        radioWrapClassName="form-check"
        radioWrapTag="div"
        value={state.value} // This line has been added
        onChange={(e) => setState({ value: e.target.value })}
      >
        <Radio
          label="#radio-1"
          radioClass="iradio_square-blue"
          value="radio1"
        />
        <Radio
          label="#radio-1"
          radioClass="iradio_square-blue"
          value="radio2"
        />
      </RadioGroup>
      <div>{state.value}</div>
    </div>
  );
}

export default App;
```

I've updated the website examples so they would be more verbose.

Let me know if there is still an issue.

**Comment by victorpopkov** [comment]
Closing this for now. Feel free to open a new issue if the problem persists.

Maybe in the future release, the `value` prop requirement in the `RadioGroup` will become optional.
